# GitHub Sponsors configuration
# Add or adjust providers as needed. If your org/user is not yet in GitHub Sponsors, the button will appear once approved.
# Docs: https://docs.github.com/sponsors/getting-started-with-github-sponsors/about-github-sponsors-for-open-source-contributors

github: IO-Aerospace-software-engineering

